spring.application.name=library-management

# SQLite Configuration
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:library.db

# JPA Configuration - Schimb? din create-drop în update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Logging
logging.level.org.springframework.security=DEBUG
server.port=8081

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=truering.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true